name: Build and Release MuseEase

on:
  push:
    branches:
      - main
  
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyQt6 pyinstaller

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name MuseEase --hidden-import PyQt6 main.py

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: museease
          path: dist/MuseEase.exe

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: museease
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/MuseEase.exe
          tag_name: v0.0.${{ github.run_number }}
          release_name: "PyQt App v1.0.${{ github.run_number }}"
          body: "Latest release of MuseEase"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
