name: Hello World Test

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

jobs:
  hello-world:
    runs-on: windows-latest  # Use Windows instead of Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Clones the repo
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Hello World Script
        run: python hello.py
