name: Build and Release MuseEase

on:
  push:
    branches:
      - main

  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-latest # Running tests on Windows for consistency

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-qt numpy sounddevice PyQt6

      - name: Run Automated Tests
        run: pytest automatic_test.py --tb=short --disable-warnings

  build-windows:
    needs: test
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyQt6 pyinstaller
          pip install pytest pytest-qt numpy sounddevice PyQt6

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --add-data "MVP;MVP" --add-data "Instruments;Instruments" --add-data "Saves;Saves" --windowed --name MuseEase --hidden-import PyQt6 main.py

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: museease-windows
          path: dist/MuseEase.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyQt6 py2app

      - name: Build Executable with py2app (macOS)
        run: |
          python setup.py py2app

      - name: List contents of dist directory (macOS) # New step to list dist directory
        run: ls -l dist/

      - name: zip the .app file
        run: |
          zip -r MuseEase.app.zip . -i MuseEase.app

      - name: Upload Build Artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: museease-macos
          path: dist/MuseEase.app.zip

  release:
    needs: [build-windows] # Removed build-macos from dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: museease-windows
          path: dist/

      # - name: Download Build Artifact (macOS)
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: museease-macos
      #     path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/MuseEase.exe
            # dist/MuseEase.app.zip  # Commented out for macOS artifact
          tag_name: v0.0.${{ github.run_number }}
          release_name: "PyQt App v1.0.${{ github.run_number }}"
          body: "Latest release of MuseEase"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
